export const SECTIONS = [
  { id: 'users', label: 'Usuarios', category: 'GENERAL' },
  { id: 'categories', label: 'Categorías', category: 'MENÚ' },
  { id: 'items', label: 'Platos / Ítems', category: 'MENÚ' },
  { id: 'variants', label: 'Variantes', category: 'MENÚ' },
  { id: 'modifier-groups', label: 'Grupos de Modif.', category: 'MENÚ' },
  { id: 'modifiers', label: 'Modificadores', category: 'MENÚ' },
  { id: 'suppliers', label: 'Proveedores', category: 'LOGÍSTICA / SALUD' },
  { id: 'ingredients', label: 'Ingredientes', category: 'LOGÍSTICA / SALUD' },
  { id: 'dietary-tags', label: 'Etiquetas Dietéticas', category: 'LOGÍSTICA / SALUD' },
  { id: 'allergens', label: 'Alérgenos', category: 'LOGÍSTICA / SALUD' },
  { id: 'product-tags', label: 'Etiquetas de Productos', category: 'MENÚ' },
];

export const FIELD_CONFIGS = {
  categories: [
    { name: 'name', label: 'Nombre', type: 'text', required: true },
    { name: 'parent_id', label: 'Categoría Padre', type: 'select', relation: 'categories', nullable: true },
    { name: 'subtitle', label: 'Subtítulo', type: 'text' },
    { name: 'description', label: 'Descripción', type: 'textarea' },
    { name: 'image_url', label: 'URL de Imagen', type: 'text' },
    { name: 'sort_order', label: 'Orden de Clasificación', type: 'number', default: 0 },
    { name: 'is_active', label: 'Activo', type: 'checkbox', default: true },
  ],
  items: [
    { name: 'name', label: 'Nombre', type: 'text', required: true },
    { name: 'category', label: 'Categoría', type: 'select', relation: 'categories', required: true },
    { name: 'description', label: 'Descripción', type: 'textarea' },
    { name: 'price', label: 'Precio ($)', type: 'number', required: true, min: 1 },
    { name: 'image', label: 'URL de Imagen', type: 'text', default: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=600&auto=format&fit=crop&q=60' },
    { name: 'stock_inicial', label: 'Stock Inicial', type: 'number', default: 0, hideOnEdit: true },
    { name: 'is_active', label: 'Activo', type: 'checkbox', default: true },
  ],
  variants: [
    { name: 'name', label: 'Nombre de Variante (ej: Personal, Familiar)', type: 'text', required: true },
    { name: 'menu_item_id', label: 'Plato / Ítem de Menú', type: 'select', relation: 'items', required: true },
    { name: 'sku', label: 'SKU (Código único)', type: 'text' },
    { name: 'price_override', label: 'Anulación de Precio ($)', type: 'number' },
    { name: 'sort_order', label: 'Orden de Clasificación', type: 'number', default: 0 },
    { name: 'is_available', label: 'Disponible', type: 'checkbox', default: true },
  ],
  'modifier-groups': [
    { name: 'name', label: 'Nombre del Grupo (ej: Salsas, Bebidas)', type: 'text', required: true },
    { name: 'description', label: 'Descripción', type: 'textarea' },
    { name: 'sort_order', label: 'Orden de Clasificación', type: 'number', default: 0 },
  ],
  modifiers: [
    { name: 'name', label: 'Nombre del Modificador', type: 'text', required: true },
    { name: 'modifier_group_id', label: 'Grupo de Modificadores', type: 'select', relation: 'modifier-groups', required: true },
    { name: 'price_delta', label: 'Diferencia de Precio ($)', type: 'number', default: 0 },
    { name: 'max_quantity', label: 'Cantidad Máxima Permitida', type: 'number' },
    { name: 'sort_order', label: 'Orden de Clasificación', type: 'number', default: 0 },
    { name: 'is_available', label: 'Disponible', type: 'checkbox', default: true },
  ],
  suppliers: [
    { name: 'name', label: 'Nombre del Proveedor', type: 'text', required: true },
    { name: 'contact_email', label: 'Email de Contacto', type: 'email' },
    { name: 'country', label: 'País', type: 'text' },
    { name: 'is_active', label: 'Activo', type: 'checkbox', default: true },
  ],
  ingredients: [
    { name: 'name', label: 'Nombre del Ingrediente', type: 'text', required: true },
    { name: 'supplier_id', label: 'Proveedor', type: 'select', relation: 'suppliers', nullable: true },
    { name: 'description', label: 'Descripción', type: 'textarea' },
    { name: 'image_url', label: 'URL de Imagen', type: 'text' },
    { name: 'origin_country', label: 'País de Origen', type: 'text' },
    { name: 'unit', label: 'Unidad de Medida (ej: kg, gr, lts)', type: 'text' },
    { name: 'storage_instructions', label: 'Instrucciones de Almacenamiento', type: 'textarea' },
    { name: 'is_active', label: 'Activo', type: 'checkbox', default: true },
  ],
  'dietary-tags': [
    { name: 'name', label: 'Nombre (ej: Vegano, Gluten Free)', type: 'text', required: true },
    { name: 'description', label: 'Descripción', type: 'textarea' },
    { name: 'icon_url', label: 'URL del Icono', type: 'text' },
    { name: 'badge_color', label: 'Color de Badge (ej: #FF5733 o green)', type: 'text' },
    { name: 'internal_ref_url', label: 'Enlace de Referencia Interna', type: 'text' },
  ],
  allergens: [
    { name: 'name', label: 'Nombre (ej: Maní, Lactosa)', type: 'text', required: true },
    { name: 'description', label: 'Descripción', type: 'textarea' },
    { name: 'icon_url', label: 'URL del Icono', type: 'text' },
    { name: 'severity', label: 'Gravedad (ej: Alta, Moderada)', type: 'text' },
    { name: 'internal_ref_url', label: 'Enlace de Referencia Interna', type: 'text' },
  ],
  'product-tags': [
    { name: 'name', label: 'Nombre de la Etiqueta (ej: 🔥 Popular)', type: 'text', required: true },
    { name: 'color', label: 'Color de la Etiqueta', type: 'color', required: true },
  ],
};
